### PR TITLE
Support for multiple collection volumes and named parameters.

### PR DESCRIPTION
**Pull request by r-clancy**
This still needs to more discussion before being merged...

- How do multiple collections effect indexing and searching?
- Do we pass the name of the collections to search as well?
  - If so, we need to pass in multiple topic files as well.

### CODE REVIEW

**Comment by r-clancy** [comment]
As it stands, the command to support multiple collections would be as follows:

```
python run.py prepare \
    --repo anserini-test --tag latest \
    --collection_name robust04,core17 \
    --collection_path /home/ryan/sync/ir/collections/disk45,/home/ryan/sync/ir/collections/NYTcorpus
```

with index being called as `sh index robust04,core17`

**Comment by lintool** [comment]
Should we just assume that  whatever is in `--collection_name foo` will be at path `/x/yz/foo`?

This would save an additional parameter...

**Comment by r-clancy** [comment]
Yeah, when the index script is called with `./index --collections a b c` we would assume the collections are mounted at `/index/collections/{a,b,c}`.

When running `jig` itself we'll still need the `name` to `path` mapping:
```
python run.py prepare \
    --repo rclancy/anserini-test --tag latest \
    --collections [name]=[path] [name]=[path] ...
```

This PR also adds support for named parameters (I'm also updating `anserini-docker` to support it) so we can settle on some names and update the [docs](https://github.com/osirrc2019/jig/blob/multiple-collections/README.md).

**Comment by lintool** [comment]
ah got it. thanks for the explanation.

**Pull request merged**
