### PR TITLE
Mac and Linux version of init.sh

### PR DESCRIPTION
**Pull request by andrewtrotman**
This version of init.sh works on Mac and probably on Linux - I don't have a Linux box handy to try it on.

### CODE REVIEW

**Comment by r-clancy** [comment]
Would just using `curl` for both Mac and Linux instead of changing between the two work instead of changing between the two?

**Comment by lintool** [comment]
Agreed, let’s not fork code paths...

**Comment by andrewtrotman** [comment]
I’m happy with that ever solution works best for everyone.

Andrew.

**Comment by r-clancy** [comment]
I fixed it in https://github.com/osirrc2019/jig/commit/e6027125734b5fce0103c3558dc4de091b366d72 - thanks for noticing the issue with Macs!

**Pull request closed without merging**
